function [] = MvD_3_1_fn_(pdf,Spt,V,n,nm)
%Special designed for GGG
%This function compare the continous PDF against the collected Data and its
%pmf generated by Ut_Vector_Analysis.
%The following is Pdf_Cdf_Plot
Q = [];
cdf = [];
cd = 0;
for i = 1 : length(Spt)
    d = pdf (Spt(i));
    cd = cd+d;
end
C=1/cd;
cd = 0;
for i = 1 : length(Spt)
    d = C.*pdf (Spt(i));
    Q = [ Q , d ];
    cd = cd+d;
    cdf= [cdf, cd];
end
%The following is Ut_Vector_Analysis
V=sort(V);
 %The following is PMF+CMF Generator
%This Algorithm seperates the vector into n portions and then round nearby
%elements into the median of these portions.
if n == 0
    x = V; 
else
    V=sort(V);
Vr=[];
z=(V(end)-V(1))/n;
W=[V(1)];
U=[];
for i=0:n
    U=[U,V(1)+i.*z];
end
for i=0.5:(n-0.5)
    W=[W,V(1)+i.*z];
end
W=[W,W(end),W(end)];
U=[U,U(end),U(end)];
for i=1:length(V)
    while length(Vr)<i
        for j= 0: length(W)
            if U(j+1)<= V(i) && V(i)<= U(j+2)
                V(i)= W(j+2);
                Vr=[Vr,V(i)];
                break    
            end
        end
    end
end
x=Vr;
end
% Vector-element-repetition-eliminate-function
% this function eliminate the same terms of a vector 
K=[];
for i=1:length(x)-1
    if x(i)~=x(i+1)
        K =[K,x(i)];
    end
    w=[K,x(end)];
end
%this function captures the frequency of a vector
y=[];
z=1;
for i=1:length(V)-1
    if V(i)==V(i+1)
        z=z+1;
    else
      y=[y,z];
      z=1;
    end
    f=[y,z];
end
y=f;
%now we have z carrying the value of x-axis with y carrying the frequency
%of each element within vector x.
S=sum(y);
Y=[];
    for i=y
    Y=[Y,i/S];
    end
    %Vector F captures all the frequencies.
    F=[0];
    for j=1:length(Y)
        F=[F,F(end)+Y(j)];
    end
    F(1)=[];
%Now Plot both graphs:
 tiledlayout(2,2)
%First is PDF
    nexttile
    plot (Spt,Q,'b',w,Y,'rx')
    legend('PDF','PMF')
    title('pd/mf')
    xlabel('value'),ylabel('density/mass')
    %2nd plot 
    nexttile
    plot(Spt,cdf,'b',w,F,'rx')
    legend('CDF','CMF')
    xlabel('value'),ylabel('cumulative density')
    title('cdf')
     %3rd Plot
    nexttile
    bar(w,Y)
    xlabel('value'),ylabel('density')
    title('bar pdf')
    %4th plot
    %Data for Pie chart
    if nm > length(F)
       nm = length (F);
    end
    nn = 0;
    while abs(nn - nm) > 10^-3 
        nn = nn + 1;
    end
    Winners_weight=F(nn);
    Losers_weight=1-Winners_weight;
    nexttile
    X = [Winners_weight,Losers_weight];
    lables = {'People Succeeded', 'people failed'};
    pie(X,lables)
    title('Real Time Simulation - 10,000 Trial')
end